env: 
  IMAGE_NAME: "vllm-xpu-test:py312"
agents:
  queue: Intel-XPU-B60

steps:
  - label: "Build XPU image"
    command: |
      chmod +x .buildkite/test-check/scripts/image-build-xpu.sh
      .buildkite/test-check/scripts/image-build-xpu.sh 

  - label: "Run test on XPU"  
    command: |
      chmod +x .buildkite/test-check/scripts/test-check-xpu.sh
      .buildkite/test-check/scripts/test-check-xpu.sh