####
#
# The following example shows how a model can be quantized with
# mixed precision entirely with primitives within `compressed-tensors`.
#
# Attention layers are quantized to FP8 (weights + dynamic per-token activations)
# and MLP layers are quantized to NVFP4 (weights + locally dynamic activations).
#
# The config is defined in `./mixed_precision_config.json`, which uses
# regex-based targets to route different layer types to different schemes.
#
####

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import math
from pathlib import Path

import torch
from compressed_tensors.compressors import ModelCompressor
from compressed_tensors.offload import update_offload_parameter
from compressed_tensors.quantization import (
    QuantizationConfig,
    QuantizationStrategy,
    apply_quantization_config,
)
from compressed_tensors.quantization.utils import calculate_qparams, generate_gparam
from datasets import load_dataset
from torch.utils.data import DataLoader, RandomSampler
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, DefaultDataCollator


config_file = Path(__file__).parent / "mixed_precision_config.json"
MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
output_dir = "./Meta-Llama-3-8B-Instruct-FP8-NVFP4"
device = "cuda:0" if torch.cuda.is_available() else "cpu"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map=device, torch_dtype="auto"
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

config = QuantizationConfig.model_validate_json(config_file.read_text())

apply_quantization_config(model, config)


def update_scales_hook(
    module: torch.nn.Module, input: torch.Tensor, _output: torch.Tensor
):
    quantization_scheme = getattr(module, "quantization_scheme", None)
    if not quantization_scheme:
        return

    # -- weight scales --
    # The weight calibration differs between the two schemes:
    #
    # FP8 (attention layers): uses CHANNEL strategy, so we compute
    #   per-output-channel min/max and derive one scale per channel.
    #
    # NVFP4 (MLP layers): uses TENSOR_GROUP strategy with group_size=16,
    #   so we reshape the weight into groups, compute per-group min/max,
    #   and derive a scale per group. NVFP4 also requires a global_scale
    #   (generated by generate_gparam) that maps the per-group FP8 scales
    #   into the full FP8 dynamic range. The global_scale is passed into
    #   calculate_qparams to produce FP8-dtype group scales.
    quantization_args = getattr(quantization_scheme, "weights", None)
    if quantization_args is not None:
        weight = module.weight.data
        group_size = quantization_args.group_size
        strategy = quantization_args.strategy

        if strategy == QuantizationStrategy.TENSOR_GROUP:
            # NVFP4: reshape into groups and compute per-group min/max
            reshaped = weight.unflatten(
                -1, (math.ceil(weight.shape[-1] / group_size), group_size)
            )
            min_val = reshaped.amin(dim=-1)
            max_val = reshaped.amax(dim=-1)

            # First compute the global scales, then derive per-group weight
            # scales. generate_gparam expects tensor-level min/max (scalars)
            # and produces global_scale = (fp8_max * fp4_max) / max(abs(tensor))
            # which maps per-group FP8 scales into the full FP8 dynamic range.
            tensor_min, tensor_max = torch.aminmax(weight)
            weight_global_scale = generate_gparam(tensor_min, tensor_max)
            # Note: you can also directly use module.weight_global_scale.copy_(weight_global_scale)
            # udate_offload_parameter is used here to demonstrate how to update the offloaded parameter in case the model is offloaded to CPU or disk.
            update_offload_parameter(module, "weight_global_scale", weight_global_scale)

            scale, _ = calculate_qparams(
                min_val, max_val, quantization_args, global_scale=weight_global_scale
            )
            update_offload_parameter(module, "weight_scale", scale)

            # input_global_scale: per-group input scales are computed dynamically
            # at runtime, but the global scale is a static per-tensor scalar that
            # must be calibrated from the data
            input_min, input_max = torch.aminmax(input[0])
            input_global_scale = generate_gparam(input_min, input_max)
            update_offload_parameter(module, "input_global_scale", input_global_scale)
        else:
            # FP8: per-output-channel min/max (one scale per row)
            min_val = weight.amin(dim=-1, keepdim=True)
            max_val = weight.amax(dim=-1, keepdim=True)
            scale, _ = calculate_qparams(min_val, max_val, quantization_args)
            update_offload_parameter(module, "weight_scale", scale)


model.apply(lambda module: module.register_forward_hook(update_scales_hook))


DATASET_ID = "HuggingFaceH4/ultrachat_200k"
DATASET_SPLIT = "train_sft"
NUM_CALIBRATION_SAMPLES = 256
MAX_SEQUENCE_LENGTH = 2048

# Load and preprocess calibration dataset
ds = load_dataset(DATASET_ID, split=f"{DATASET_SPLIT}[:{NUM_CALIBRATION_SAMPLES}]")
ds = ds.shuffle(seed=42)


def preprocess(example):
    return {
        "text": tokenizer.apply_chat_template(
            example["messages"],
            tokenize=False,
        )
    }


ds = ds.map(preprocess)


def tokenize(sample):
    return tokenizer(
        sample["text"],
        padding=False,
        max_length=MAX_SEQUENCE_LENGTH,
        truncation=True,
        add_special_tokens=False,
    )


tokenized_dataset = ds.map(tokenize, remove_columns=ds.column_names)
data_loader = DataLoader(
    tokenized_dataset,
    batch_size=1,
    collate_fn=DefaultDataCollator(),
    sampler=RandomSampler(tokenized_dataset),
)

with torch.no_grad():
    for idx, sample in tqdm(enumerate(data_loader), desc="Running calibration"):
        sample = {k: v.to(model.device) for k, v in sample.items()}
        _ = model(**sample)


compressor = ModelCompressor.from_pretrained_model(model)
compressor.compress_model(model)

# Save the compressed model and update config with quantization details.
# The compression format is inferred per-module by checking each format's
# `can_compress(module_type, scheme)` in priority order
# (see compressed_tensors/compressors/format.py):
#   - Attention layers (FP8): use "float-quantized" format, which stores
#     weight_scale alongside the quantized weights
#   - MLP layers (NVFP4): use "nvfp4-pack-quantized" format, which packs
#     two FP4 values per byte and stores weight_scale (FP8), weight_global_scale,
#     and input_global_scale
#
# Because the model contains modules with different compression formats,
# the overall model format is reported as "mixed-precision" in the saved config
model.save_pretrained(output_dir)
compressor.update_config(output_dir)
